# Container used for the postgres db seed data
FROM node:17-alpine

WORKDIR /usr/src/app

COPY prisma ./prisma
COPY src/db ./src/db
COPY src/utils ./src/utils
COPY .env ./

RUN npm i @prisma/client  @faker-js/faker  file-type-cjs glob prisma-dbml-generator


EXPOSE 8080

